CREATE TABLE IF NOT EXISTS player_season_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER NOT NULL,
    team_id INTEGER,
    season VARCHAR(20) NOT NULL,
    league VARCHAR(10),
    age INTEGER,
    position VARCHAR(20),
    games_played INTEGER,
    games_started INTEGER,
    minutes_total INTEGER,
    minutes_per_game FLOAT,
    fg INTEGER,
    fga INTEGER,
    fg_pct FLOAT,
    tp INTEGER,
    tpa INTEGER,
    tp_pct FLOAT,
    twop INTEGER,
    twopa INTEGER,
    twop_pct FLOAT,
    efg_pct FLOAT,
    ft INTEGER,
    fta INTEGER,
    ft_pct FLOAT,
    orb INTEGER,
    drb INTEGER,
    trb INTEGER,
    ast INTEGER,
    stl INTEGER,
    blk INTEGER,
    tov INTEGER,
    pf INTEGER,
    pts INTEGER,
    pts_per_game FLOAT,
    per FLOAT,
    ts_pct FLOAT,
    three_p_ar FLOAT,
    ft_r FLOAT,
    orb_pct FLOAT,
    drb_pct FLOAT,
    trb_pct FLOAT,
    ast_pct FLOAT,
    stl_pct FLOAT,
    blk_pct FLOAT,
    tov_pct FLOAT,
    usg_pct FLOAT,
    ows FLOAT,
    dws FLOAT,
    ws FLOAT,
    ws_per48 FLOAT,
    obpm FLOAT,
    dbpm FLOAT,
    bpm FLOAT,
    vorp FLOAT,
    source VARCHAR(50),
    fetched_at DATETIME,
    FOREIGN KEY (player_id) REFERENCES players(player_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    UNIQUE(player_id, season)
);